"""
AI Dev Kit Version File
"""
VERSION_RC = 0
VERSION_EPIC = 6
VERSION_STORY = 9
VERSION_TASK = 9
VERSION_BUILD = 1
VERSION_STRING = f"{VERSION_RC}.{VERSION_EPIC}.{VERSION_STORY}.{VERSION_TASK}+{VERSION_BUILD}"
# Current: 0.6.9.9+1
