#!/usr/bin/env python3
"""
Sync maintainer sources into greenfield-install/ (FR-110 / E06:S09:T21).

Idempotent copy of packages/frameworks/ plus generated adopter README and footprint
report. Use --check in CI to fail when sources change without re-sync.

Autofix-class PR reconciliation:
`--autofix-reconcile` performs dual-tree correction (Mode A vs Mode B) and then
re-runs the existing sync + drift-check invariant.
"""

from __future__ import annotations

import argparse
import fnmatch
import hashlib
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Tuple

try:
    import yaml
except ImportError:
    yaml = None  # type: ignore[assignment]


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = REPO_ROOT / "scripts" / "greenfield-install-manifest.yaml"

README_TEMPLATE = """# AI Dev Kit — lean adopter install tree (FR-110)

**Vendor or copy this directory** into your project (e.g. `vendor/ai-dev-kit/`). It contains **only** framework packages (~11 MiB) — not the full maintainer repository.

## Quick start

From your **host project root** (parent of this vendor tree):

```bash
python3 "vendor/ai-dev-kit/packages/frameworks/workflow-mgt/scripts/install_greenfield_path.py" \\
  --project-root "." \\
  --non-interactive
```

Adjust `vendor/ai-dev-kit/` to match your layout. Install scripts live under `packages/frameworks/*/scripts/`.

## Install error codes (FR-108 / FR-111)

When acquisition or install fails, report **SemVer banner + `ADK-*` code** ([UXR-016](https://github.com/RMS-Ltd/ai-dev-kit/blob/main/docs/kanban/fr-br/UXR-016-install-setup-interactive-feedback-external-semver-version.md)). Run vendor preflight before installers:

```bash
python3 vendor/ai-dev-kit/packages/frameworks/workflow-mgt/scripts/verify_vendor_tree.py \\
  --vendor-root vendor/ai-dev-kit
```

Lookup: [framework-dependency-troubleshooting-guide.md](https://github.com/RMS-Ltd/ai-dev-kit/blob/main/docs/documentation/user-docs/framework-dependency-troubleshooting-guide.md#install-error-codes-adk) (registry **1.1.0**).

## Download integrity (SHA-256)

Release tarballs ship with a matching `.sha256` sidecar on [GitHub Releases](https://github.com/RMS-Ltd/ai-dev-kit/releases). Verify before extract:

```bash
gh release download v{semver} --repo RMS-Ltd/ai-dev-kit \\
  -p 'greenfield-install-v{semver}.tar.gz' \\
  -p 'greenfield-install-v{semver}.tar.gz.sha256' -D /tmp/adk-dl
shasum -a 256 -c /tmp/adk-dl/greenfield-install-v{semver}.tar.gz.sha256
# Expected: greenfield-install-v{semver}.tar.gz: OK
```

Pin the SHA-256 from `greenfield-install-v{semver}.tar.gz.sha256` (release sidecar).

## Update upstream

- **Submodule / sparse checkout:** `cd vendor/ai-dev-kit && git fetch --tags && git checkout tags/v{semver}` (see [releases](https://github.com/RMS-Ltd/ai-dev-kit/releases)).
- **Copy refresh:** re-copy this tree from a tagged `greenfield-install/` export or verified `greenfield-install-v{semver}.tar.gz` on [releases](https://github.com/RMS-Ltd/ai-dev-kit/releases).
- **GitHub Container Registry (alternate):** when submodules are blocked, pull the lean image and copy `/opt/adk/` into `vendor/ai-dev-kit/` (same bytes as this tree; [ADR-021](https://github.com/RMS-Ltd/ai-dev-kit/blob/main/docs/architecture/standards-and-adrs/ADR-021-greenfield-install-ghcr-delivery-channel.md)):

  ```bash
  # Replace v{semver} with the external SemVer core you are pinning.
  docker pull ghcr.io/rms-ltd/ai-dev-kit-greenfield:v{semver}
  mkdir -p vendor/ai-dev-kit
  cid=$(docker create ghcr.io/rms-ltd/ai-dev-kit-greenfield:v{semver})
  docker cp "$cid:/opt/adk/." vendor/ai-dev-kit/
  docker rm "$cid"
  ```

  Optional digest pin: `docker pull ghcr.io/rms-ltd/ai-dev-kit-greenfield@sha256:<digest>` (see [Packages](https://github.com/RMS-Ltd/ai-dev-kit/pkgs/container/ai-dev-kit-greenfield)).

## Documentation

- [INSTALL_IN_YOUR_PROJECT.md](https://github.com/RMS-Ltd/ai-dev-kit/blob/main/INSTALL_IN_YOUR_PROJECT.md#lean-vendor-install-greenfield-install--fr-110)
- [FR-110](https://github.com/RMS-Ltd/ai-dev-kit/blob/main/docs/kanban/fr-br/FR-110-lean-adopter-distribution-footprint-and-vendor-bundle.md)

## Maintainer note

This tree is generated by `scripts/sync_greenfield_install.py` from `packages/frameworks/`. Do not edit copied files here — change sources and re-sync.
"""


@dataclass(frozen=True)
class Manifest:
    dest_root: Path
    copy_trees: List[Tuple[Path, Path]]
    ignore_globs: List[str]


def _load_manifest(path: Path) -> Manifest:
    if yaml is None:
        raise RuntimeError("PyYAML required: pip install pyyaml")
    raw: Dict[str, Any] = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    dest_root = REPO_ROOT / str(raw.get("dest_root", "greenfield-install"))
    copy_trees: List[Tuple[Path, Path]] = []
    for entry in raw.get("copy_trees") or []:
        copy_trees.append(
            (REPO_ROOT / entry["src"], dest_root / entry["dest"])
        )
    ignore_globs = list(raw.get("ignore_globs") or [])
    return Manifest(dest_root=dest_root, copy_trees=copy_trees, ignore_globs=ignore_globs)


def _ignored(rel_posix: str, ignore_globs: List[str]) -> bool:
    for pattern in ignore_globs:
        if fnmatch.fnmatch(rel_posix, pattern):
            return True
        # Also match path segments for patterns like **/__pycache__
        parts = rel_posix.split("/")
        pattern_parts = [p for p in pattern.split("/") if p and p != "**"]
        for part in parts:
            for pattern_part in pattern_parts:
                if fnmatch.fnmatch(part, pattern_part):
                    return True
    return False


def _git_ls_files(prefix: Path) -> List[str]:
    rel_prefix = prefix.relative_to(REPO_ROOT).as_posix()
    result = subprocess.run(
        ["git", "ls-files", "--", rel_prefix],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        stderr = (result.stderr or "").strip()
        stdout = (result.stdout or "").strip()
        details = stderr or stdout or "no output"
        print(
            f"warning: `git ls-files` failed for '{rel_prefix}' "
            f"(exit code {result.returncode}): {details}",
            file=sys.stderr,
        )
        return []
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


def _iter_files(root: Path, ignore_globs: List[str]) -> Iterable[Path]:
    if not root.exists():
        return
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(root).as_posix()
        if _ignored(rel, ignore_globs):
            continue
        yield path


def _source_relative_paths(src: Path, ignore_globs: List[str]) -> List[str]:
    """Paths under src using git index casing (Linux-safe)."""
    tracked = _git_ls_files(src)
    if tracked:
        prefix = src.relative_to(REPO_ROOT).as_posix().rstrip("/") + "/"
        rels: List[str] = []
        for entry in tracked:
            if not entry.startswith(prefix):
                continue
            rel = entry[len(prefix) :]
            if _ignored(rel, ignore_globs):
                continue
            rels.append(rel)
        return sorted(rels)
    return sorted(p.relative_to(src).as_posix() for p in _iter_files(src, ignore_globs))


def _file_hash(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _tree_fingerprint(root: Path, ignore_globs: List[str], *, git_index: bool = False) -> Dict[str, str]:
    if git_index:
        return {
            rel: _file_hash(root / rel)
            for rel in _source_relative_paths(root, ignore_globs)
        }
    return {
        p.relative_to(root).as_posix(): _file_hash(p)
        for p in _iter_files(root, ignore_globs)
    }


def _dir_size_bytes(root: Path, ignore_globs: List[str]) -> int:
    total = 0
    for path in _iter_files(root, ignore_globs):
        total += path.stat().st_size
    return total


def _mib(nbytes: int) -> str:
    return f"{nbytes / (1024 * 1024):.2f}"


def _validate_safe_dest(dest: Path) -> None:
    resolved_dest = dest.resolve()
    resolved_repo = REPO_ROOT.resolve()
    if resolved_dest == resolved_dest.anchor:
        raise ValueError(f"Refusing to delete unsafe destination: {resolved_dest}")
    try:
        resolved_dest.relative_to(resolved_repo)
    except ValueError as exc:
        raise ValueError(
            f"Refusing to delete destination outside repository root: {resolved_dest}"
        ) from exc


def _copy_tree(src: Path, dest: Path, ignore_globs: List[str]) -> int:
    if not src.is_dir():
        raise FileNotFoundError(f"Source tree missing: {src}")
    _validate_safe_dest(dest)
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True, exist_ok=True)
    rel_paths = _source_relative_paths(src, ignore_globs)
    for rel in rel_paths:
        src_path = src / rel
        dest_path = dest / rel
        dest_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src_path, dest_path)
    return len(rel_paths)


def _resolve_internal_version() -> str:
    """Read current internal version from configured version.py."""
    version_file = REPO_ROOT / "src" / "ai_dev_kit" / "version.py"
    config_path = REPO_ROOT / "rw-config.yaml"
    if config_path.exists() and yaml is not None:
        raw: Dict[str, Any] = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
        configured = raw.get("version_file")
        if isinstance(configured, str) and configured.strip():
            version_file = REPO_ROOT / configured.strip()
    content = version_file.read_text(encoding="utf-8")
    # Match: VERSION_STRING = <optional python string prefix><quoted value>
    # Optional prefixes: r/R, u/U, b/B, f/F. Group 1 captures quote char (' or "),
    # and \1 enforces the same closing quote; group 2 captures the version value.
    version_string_pattern = re.compile(
        r"""^VERSION_STRING\s*=\s*(?:[rRuUbBfF])?(['"])(.*?)\1\s*$"""
    )
    for line in content.splitlines():
        line = line.strip()
        match = version_string_pattern.match(line)
        if match:
            candidate = match.group(2)
            if "{" not in candidate:
                return candidate
    values: Dict[str, int] = {}
    for key in ("VERSION_RC", "VERSION_EPIC", "VERSION_STORY", "VERSION_TASK", "VERSION_BUILD"):
        for line in content.splitlines():
            line = line.strip()
            if line.startswith(f"{key} ="):
                raw_value = line.split("=", 1)[1].strip()
                if not re.fullmatch(r"[+-]?\d+", raw_value):
                    raise RuntimeError(
                        f"Invalid integer value for {key} in {version_file}: {raw_value!r}"
                    )
                values[key] = int(raw_value)
                break
    return (
        f"{values['VERSION_RC']}."
        f"{values['VERSION_EPIC']}."
        f"{values['VERSION_STORY']}."
        f"{values['VERSION_TASK']}+{values['VERSION_BUILD']}"
    )


def _resolve_current_semver_core() -> str:
    """Convert internal version to outward SemVer and strip +BUILD."""
    internal = _resolve_internal_version()
    converter = (
        REPO_ROOT
        / "packages"
        / "frameworks"
        / "workflow-mgt"
        / "scripts"
        / "version"
        / "semver_converter.py"
    )
    result = subprocess.run(
        ["python3", str(converter), internal],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        stderr_msg = (result.stderr or "").strip()
        stdout_msg = (result.stdout or "").strip()
        raise RuntimeError(
            f"Failed to resolve SemVer for {internal}. stderr: {stderr_msg}, stdout: {stdout_msg}"
        )
    return result.stdout.strip().split("+", 1)[0]


def _write_readme(dest_root: Path) -> None:
    semver = _resolve_current_semver_core()
    content = README_TEMPLATE.format(semver=semver)
    (dest_root / "README.md").write_text(content.strip() + "\n", encoding="utf-8")


def _write_footprint(dest_root: Path, manifest: Manifest) -> None:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    dest_bytes = _dir_size_bytes(dest_root, manifest.ignore_globs)
    frameworks_src = REPO_ROOT / "packages" / "frameworks"
    src_bytes = _dir_size_bytes(frameworks_src, manifest.ignore_globs)
    # NOTE: This row is an intentionally fixed historical reference baseline.
    # It is not computed dynamically to preserve a stable comparison point across runs.
    # Keep the date/value in sync via periodic manual review as repository size evolves.
    lines = [
        "# greenfield-install footprint",
        "",
        f"**Measured:** {ts}",
        "",
        "| Tree | MiB |",
        "| ---- | --- |",
        f"| `greenfield-install/` | {_mib(dest_bytes)} |",
        f"| `packages/frameworks/` (source) | {_mib(src_bytes)} |",
        "| Full repo (tracked baseline, 2026-06-05) | ~27.00 |",
        "",
        "**AC1 target:** lean tree ≤ 50% of full repo (~≤14 MiB).",
        "",
        "Regenerate: `python scripts/sync_greenfield_install.py`",
        "",
    ]
    (dest_root / "FOOTPRINT.md").write_text("\n".join(lines), encoding="utf-8")


def sync(manifest: Manifest) -> int:
    manifest.dest_root.mkdir(parents=True, exist_ok=True)
    total = 0
    for src, dest in manifest.copy_trees:
        count = _copy_tree(src, dest, manifest.ignore_globs)
        total += count
        print(
            f"Synced {src.relative_to(REPO_ROOT)} -> "
            f"{dest.relative_to(REPO_ROOT)} ({count} files)"
        )
    _write_readme(manifest.dest_root)
    _write_footprint(manifest.dest_root, manifest)
    print(f"greenfield-install/ ready ({total} framework files)")
    return 0


def check(manifest: Manifest) -> int:
    errors: List[str] = []
    for src, dest in manifest.copy_trees:
        if not dest.exists():
            errors.append(f"Missing dest tree: {dest.relative_to(REPO_ROOT)}")
            continue
        src_fp = _tree_fingerprint(src, manifest.ignore_globs, git_index=True)
        # Dest uses git index when tracked (Linux-safe casing vs packages/frameworks).
        dest_fp = _tree_fingerprint(dest, manifest.ignore_globs, git_index=True)
        if src_fp != dest_fp:
            missing = sorted(set(src_fp) - set(dest_fp))
            extra = sorted(set(dest_fp) - set(src_fp))
            changed = sorted(
                k for k in src_fp if k in dest_fp and src_fp[k] != dest_fp[k]
            )
            if missing:
                errors.append(
                    f"{dest.relative_to(REPO_ROOT)}: {len(missing)} missing file(s), e.g. {missing[:3]}"
                )
            if extra:
                errors.append(
                    f"{dest.relative_to(REPO_ROOT)}: {len(extra)} extra file(s), e.g. {extra[:3]}"
                )
            if changed:
                errors.append(
                    f"{dest.relative_to(REPO_ROOT)}: {len(changed)} changed file(s), e.g. {changed[:3]}"
                )
    readme = manifest.dest_root / "README.md"
    if not readme.is_file():
        errors.append("Missing greenfield-install/README.md")
    footprint = manifest.dest_root / "FOOTPRINT.md"
    if not footprint.is_file():
        errors.append("Missing greenfield-install/FOOTPRINT.md")
    if errors:
        for err in errors:
            print(f"DRIFT: {err}", file=sys.stderr)
        print(
            "Dual-tree drift guard fired.\n"
            "- If you edited only `packages/frameworks/**` (Mode A), re-run sync to regenerate "
            "`greenfield-install/packages/frameworks/**`.\n"
            "- If you edited only `greenfield-install/packages/frameworks/**` (Mode B), copy "
            "changed framework files back into `packages/frameworks/**` and then regenerate "
            "the mirror.\n"
            "\n"
            "For autofix-class PR remediation, see:\n"
            "  .github/workflows/greenfield-autofix-reconcile.yml\n"
            "\n"
            "Manual remediation quickstart:\n"
            "  python scripts/sync_greenfield_install.py\n",
            file=sys.stderr,
        )
        return 1
    print("greenfield-install/ in sync with sources")
    return 0


def _parse_changed_files_csv(changed_files: str) -> List[str]:
    parts = [p.strip() for p in (changed_files or "").split(",")]
    return [p for p in parts if p]


def _compute_changed_files(diff_base: str, diff_head: str) -> List[str]:
    # Git diff outputs repo-relative file paths.
    result = subprocess.run(
        ["git", "diff", "--name-only", f"{diff_base}...{diff_head}"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            "Failed to compute diff for autofix reconciliation: "
            f"exit={result.returncode} stderr={(result.stderr or '').strip()}"
        )
    return [line.strip() for line in (result.stdout or "").splitlines() if line.strip()]


def _classify_autofix_mode(changed_files: List[str]) -> str:
    # Mode A: sources touched but mirror not touched.
    # Mode B: mirror touched but sources not touched.
    # Anything else (or neither) is ambiguous / non-autofix.
    norm = [p.replace("\\", "/") for p in changed_files]
    src_prefix = "packages/frameworks/"
    mirror_prefix = "greenfield-install/packages/frameworks/"

    touches_src = any(p.startswith(src_prefix) for p in norm)
    touches_mirror = any(p.startswith(mirror_prefix) for p in norm)

    if touches_src and not touches_mirror:
        return "MODE_A"
    if touches_mirror and not touches_src:
        return "MODE_B"
    if not touches_src and not touches_mirror:
        return "NONE"
    return "AMBIGUOUS"


def autofix_reconcile(manifest: Manifest, *, changed_files: List[str]) -> int:
    mode = _classify_autofix_mode(changed_files)
    if mode == "NONE":
        print("autofix reconcile: no dual-tree touched; skipping")
        return 0

    if mode == "AMBIGUOUS":
        print(
            "autofix reconcile: ambiguous diff (both Mode A + Mode B trees appear touched). "
            "Refusing to guess.\n"
            "Dual-tree guidance:\n"
            "- Mode A = edit only `packages/frameworks/**` then regenerate mirror.\n"
            "- Mode B = edit only `greenfield-install/packages/frameworks/**` then copy back "
            "to `packages/frameworks/**` and regenerate mirror.\n"
            "\n"
            "Remediation workflow:\n"
            "  .github/workflows/greenfield-autofix-reconcile.yml\n",
            file=sys.stderr,
        )
        return 1

    if mode == "MODE_A":
        print("autofix reconcile: Mode A selected (sources touched only) → regenerate mirror")
        rc = sync(manifest)
        if rc != 0:
            return rc
        return check(manifest)

    # MODE_B: copy changed mirror files back into the source tree first.
    print("autofix reconcile: Mode B selected (mirror touched only) → copy back then regenerate mirror")
    mirror_prefix = "greenfield-install/packages/frameworks/"
    copied_any = 0

    for p in changed_files:
        norm = p.replace("\\", "/")
        if not norm.startswith(mirror_prefix):
            continue
        rel = norm[len(mirror_prefix) :]
        src_path = REPO_ROOT / "greenfield-install/packages/frameworks" / rel
        dest_path = REPO_ROOT / "packages/frameworks" / rel
        if not src_path.is_file():
            continue
        dest_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src_path, dest_path)
        copied_any += 1

    if copied_any == 0:
        print(
            "autofix reconcile: Mode B selected but no mirror-side files were copyable "
            "(changed-files likely includes deletions/renames). Refusing to guess.",
            file=sys.stderr,
        )
        return 1

    rc = sync(manifest)
    if rc != 0:
        return rc
    return check(manifest)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--manifest",
        type=Path,
        default=DEFAULT_MANIFEST,
        help="Path to greenfield-install-manifest.yaml",
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--check",
        action="store_true",
        help="Verify dest matches sources; exit 1 on drift",
    )
    group.add_argument(
        "--sync",
        action="store_true",
        help="Copy sources into greenfield-install/ (default)",
    )
    group.add_argument(
        "--autofix-reconcile",
        action="store_true",
        help="Classify Mode A vs Mode B from diff input, apply dual-tree correction, then enforce drift-check",
    )
    parser.add_argument(
        "--changed-files",
        type=str,
        default=None,
        help="Comma-separated repo-relative changed file paths (used for Mode A/B classification)",
    )
    parser.add_argument(
        "--diff-base",
        type=str,
        default=None,
        help="Git ref used to compute PR diff base for Mode A/B classification",
    )
    parser.add_argument(
        "--diff-head",
        type=str,
        default=None,
        help="Git ref used to compute PR diff head for Mode A/B classification",
    )
    args = parser.parse_args()
    manifest = _load_manifest(args.manifest.resolve())

    if args.autofix_reconcile:
        if args.check or args.sync:
            print("--autofix-reconcile cannot be combined with --check/--sync", file=sys.stderr)
            return 2

        if args.changed_files:
            changed_files = _parse_changed_files_csv(args.changed_files)
        elif args.diff_base and args.diff_head:
            changed_files = _compute_changed_files(args.diff_base, args.diff_head)
        else:
            print(
                "autofix reconcile requires either --changed-files or both --diff-base and --diff-head",
                file=sys.stderr,
            )
            return 2

        return autofix_reconcile(manifest, changed_files=changed_files)

    if args.check:
        return check(manifest)
    return sync(manifest)


if __name__ == "__main__":
    raise SystemExit(main())
