// @ts-check

/**
 * FR-114 / E05:S09:T15 — Adopter-public sidebar IA.
 *
 * Published corpus: guides/, documentation/, developer-tools/ide-whitelist-guide.md only.
 * Maintainer corpora (Kanban, IPPs, architecture ADRs, knowledge) are excluded from
 * the docs plugin — link to GitHub blob URLs from published pages instead.
 *
 * Mapping table: portal/README.md → FR-114 allowlist.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Guides',
      items: [{type: 'autogenerated', dirName: 'guides'}],
    },
    {
      type: 'category',
      label: 'Documentation',
      items: [{type: 'autogenerated', dirName: 'documentation'}],
    },
    {
      type: 'doc',
      id: 'developer-tools/ide-whitelist-guide',
      label: 'IDE command whitelist',
    },
  ],
};

export default sidebars;
